const DATA={
 bharati:{facts:[['Location','69.4068° S, 76.1953° E'],['Elevation','~35 m'],['CHP generation','3 × 100 kVA'],['Fuel farm','~300,000 L'],['Main building capacity','47 personnel'],['Model source','NCPOR']]},
 maitri:{facts:[['Location','70.769° S, 11.735° E'],['Station type','Indian Antarctic research station'],['Power','Regulated station supply'],['Heating','Automated heating system'],['Communications','Satellite communication'],['Model source','NCPOR']]}
};
const navs=document.querySelectorAll('.nav-item');const views=document.querySelectorAll('.view');
function goTo(id){views.forEach(v=>v.classList.toggle('active-view',v.id===id));navs.forEach(n=>n.classList.toggle('active',n.dataset.target===id));window.scrollTo({top:0,behavior:'smooth'})}
navs.forEach(n=>n.addEventListener('click',()=>goTo(n.dataset.target)));
window.goTo=goTo;
function tick(){const d=new Date();const t=d.toLocaleTimeString('en-IN',{hour12:false,timeZone:'Asia/Kolkata'});document.getElementById('clock').textContent=t+' IST'}setInterval(tick,1000);tick();
function renderFacts(st='bharati'){document.getElementById('factsList').innerHTML=DATA[st].facts.map(f=>`<div class="fact"><span>${f[0]}</span><b>${f[1]}</b></div>`).join('')}
renderFacts();
document.getElementById('stationSelect').addEventListener('change',e=>{const s=e.target.value.toLowerCase();renderFacts(s);if(s==='maitri'){document.getElementById('temp').textContent='—';document.getElementById('wind').textContent='Official feed';document.getElementById('mainAlert').innerHTML='<div class="alert-icon">i</div><div><b>STATION SWITCHED · MAITRI</b><span>Environmental values are intentionally not fabricated when a live observation is not loaded in this static prototype.</span></div><button onclick="goTo(\'sources\')">Inspect sources →</button>'}else{document.getElementById('temp').textContent='-21.2°';document.getElementById('wind').textContent='12.4 m/s';document.getElementById('mainAlert').innerHTML='<div class="alert-icon">!</div><div><b>ENERGY → FUEL CASCADE DETECTED</b><span>High simulated generator load combined with a shrinking fuel endurance window.</span></div><button onclick="goTo(\'analysis\')">Inspect chain →</button>'}});
const slider=document.getElementById('loadSlider');const loadValue=document.getElementById('loadValue');function updateSim(){const reduction=Number(slider.value);loadValue.textContent=reduction+'%';const outLoad=Math.max(71,91-reduction);const fuel=Math.max(84,100-reduction*.8);const days=(16+reduction*.2).toFixed(1).replace('.0','');document.getElementById('outLoad').textContent=outLoad+'%';document.getElementById('outFuel').textContent=Math.round(fuel)+'%';document.getElementById('outDays').textContent=days+' days';document.getElementById('outRisk').textContent=reduction>=8?'MODERATE':'HIGH';document.getElementById('outcomeMessage').innerHTML=`<b>Model interpretation:</b> at a ${reduction}% reduction, the demonstration model projects generator utilization at ${outLoad}% and fuel endurance at ${days} days. This is a scenario calculation, not live equipment control.`}slider.addEventListener('input',updateSim);document.getElementById('simulateBtn').addEventListener('click',()=>{updateSim();document.getElementById('outcomeMessage').scrollIntoView({behavior:'smooth',block:'center'})});updateSim();
const sources=[
 ['VERIFIED · STATION','NCPOR — Bharati','Station location, elevation, capacities and infrastructure details used to construct the station model.','https://ncpor.res.in/pages/display/177-bharti','VERIFIED'],
 ['VERIFIED · INFRASTRUCTURE','NCPOR — Significant Achievements','Published Bharati infrastructure includes three 100 kVA CHP units and an approximately 3 lakh litre fuel farm.','https://ncpor.res.in/antarcticas/display/369-significant-achievements-','VERIFIED'],
 ['VERIFIED · OBSERVATIONS','NCPOR Polar Data Centre','Public polar-data resources provide meteorological observations from Indian polar stations.','https://pdc.ncpor.res.in/pdc/','VERIFIED'],
 ['VERIFIED · RESEARCH STATIONS','NCPOR Polar Data Centre','Research-station metadata for Indian Antarctic stations including Maitri and Bharati.','https://npdc.ncpor.res.in/npdc/research-stations.action','VERIFIED'],
 ['SIMULATED · TELEMETRY','Prototype Scenario Model','Generator load, fuel reserve and consumption values are demonstration assumptions because operational telemetry is not publicly exposed in this prototype.','#','SIMULATED'],
 ['SIMULATED · LOGISTICS','Prototype Scenario Model','Resupply window and projected endurance are used only to demonstrate consequence analysis and What-If simulation.','#','SIMULATED']
];document.getElementById('sourceGrid').innerHTML=sources.map(s=>`<article class="source-card"><div class="source-type">${s[0]}</div><h3>${s[1]}</h3><p>${s[2]}</p><span class="status ${s[4].toLowerCase()}">${s[4]}</span>${s[3]!=='#'?`<a href="${s[3]}" target="_blank" rel="noopener">Open source ↗</a>`:''}</article>`).join('');
document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
